### ISSUE TITLE
Can I build upon your work?

### ISSUE THREAD

**Issue by gabrielfougeron** [yuttie/beamer-template#1]
First of all, congratulations for your work, this beamer template looks amazing.

I am currently learning to build my own beamer style and I'd like to build upon your beamerthemecute.
I could not find a licence file in your repository. I'm thus asking for authorization to reuse and modify your work.

Thank you,

**Comment by yuttie** [comment]
@gabrielfougeron 
Thank you for trying this template.
I am so glad to hear that!

Of course it will be fine!
I added the LICENSE file a while ago, it is MIT licensed.

I hope you will be able to complete your own great theme!

**Comment by gabrielfougeron** [comment]
Thank you very much 😊😊
